# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:base)\
$directory\
[](fg:base bg:surface0)\
$git_branch\
$git_status\
[](fg:surface0 bg:surface1)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$rust\
$ruby\
[](fg:surface1 bg:surface2)\
$docker_context\
[](fg:surface2 bg:overlay0)\
$character(bg:overlay0)\
"""

right_format = "$time"

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_frappe"
command_timeout = 1000

[character]
# Note the use of Catppuccin color 'peach'
format = "[$symbol ]($style bold)"
success_symbol = "[[󰄛](fg:green bg:overlay0)[](fg:overlay0)  ](fg:rosewater)"
error_symbol = "[[󰄛](fg:red bg:overlay0)[](fg:overlay0)  ](fg:rosewater)"
vimcmd_symbol = "[[󰄛](fg:mauve bg:overlay0)[](fg:overlay0)  ](fg:rosewater)" # For use with zsh-vi-mode
vimcmd_replace_one_symbol = '[[󰄛](fg:mauve bg:overlay0)[](fg:overlay0)  ](fg:mauve)'
vimcmd_replace_symbol = '[[󰄛](fg:mauve bg:overlay0)[](fg:overlay0)  ](fg:mauve)'
vimcmd_visual_symbol = '[[󰄛](fg:yellow bg:overlay0)[](fg:overlay0)  ](fg:yellow)'

[directory]
style = "fg:red bg:base"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Projects" = " "
"Workspace" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:maroon bg:surface0"
format = '[[ $symbol $branch ]($style)]($style)'

[git_status]
style = "fg:maroon bg:surface0"
format = '[[($all_status$ahead_behind )]($style)]($style)'

[c]
symbol = " "
style = "fg:peach bg:surface1"
format = '[[ $symbol ($version) ](fg:peach bg:surface1)]($style)'

[docker_context]
symbol = " "
style = "fg:yellow bg:surface2"
format = '[[ $symbol $context ](fg:yellow bg:surface2)]($style)$path'

[elixir]
symbol = " "
style = "fg:peach bg:surface1"
format = '[[ $symbol ($version) ](fg:peach bg:surface1)]($style)'

[elm]
symbol = " "
style = "fg:peach bg:surface1"
format = '[[ $symbol ($version) ](fg:peach bg:surface1)]($style)'

[golang]
symbol = " "
style = "fg:peach bg:##cba6f7"
format = '[[ $symbol](fg:peach bg:surface1)]($style)'

[haskell]
symbol = " "
style = "fg:peach bg:surface1"
format = '[[ $symbol ($version) ](fg:peach bg:surface1)]($style)'

[java]
symbol = " "
style = "fg:peach bg:surface1"
format = '[[ $symbol ($version) ](fg:peach bg:surface1)]($style)'

[julia]
symbol = " "
style = "fg:peach bg:surface1"
format = '[[ $symbol ($version) ](fg:peach bg:surface1)]($style)'

[nodejs]
symbol = ""
style = "fg:peach bg:surface1"
format = '[[ $symbol ($version) ](fg:peach bg:surface1)]($style)'

[rust]
symbol = ""
style = "fg:peach bg:surface1"
format = '[[ $symbol ($version) ](fg:peach bg:surface1)]($style)'

[ruby]
symbol = ""
style = "fg:peach bg:surface1"
format = '[[ $symbol( $version) ](fg:peach bg:surface1)]($style)'

[time]
disabled = false
format = '[ $time](fg:rosewater)'
time_format = '%T'


# Palette definitions
[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "peach"
