color = ''
project-name = 'default'
[default]
account_id = 'acct_1IJyVILI8zcR9zK6'
device_name = 'Tomas-Guinzburg.local'
display_name = 'Amenitiz - AmenitizPay'
live_mode_api_key = 'rk_live_***********************************************************************************************TpIz'
live_mode_key_expires_at = '2024-08-27'
live_mode_pub_key = 'pk_live_51IJyVILI8zcR9zK62I8nlHtldOzJAJkYZ3IEZzqqvLsGa8idMdm5L0UEmO6sYrlt2fBkF4TZgWlDeQZDH4bjHGgM00tPx2pQ3c'
test_mode_api_key = 'rk_test_51IJyVILI8zcR9zK6YjCDT4U8cVDFxP1mCCYEsoVwqpsutDONRr51xMTEnFdCSzjXrcp0LsHTC9Wcd2W8kuG2Ru7F00KxZbQ6Gb'
test_mode_key_expires_at = '2024-08-27'
test_mode_pub_key = 'pk_test_51IJyVILI8zcR9zK6cpgq7VesarlFn6TJlNEM2O1O3OpUAKqE7tVmItbNA7gtkp72DEemAXMKrRRXDGgBFKSvi0Gd00izPXa3UT'

