color = ''
project-name = 'default'
[default]
account_id = 'acct_1IJyVILI8zcR9zK6'
device_name = 'Tomass-MacBook-Pro.local'
display_name = 'Amenitiz - AmenitizPay'
live_mode_api_key = 'rk_live_***********************************************************************************************PLWU'
live_mode_key_expires_at = '2024-05-02'
live_mode_pub_key = 'pk_live_51IJyVILI8zcR9zK62I8nlHtldOzJAJkYZ3IEZzqqvLsGa8idMdm5L0UEmO6sYrlt2fBkF4TZgWlDeQZDH4bjHGgM00tPx2pQ3c'
test_mode_api_key = 'rk_test_51IJyVILI8zcR9zK6UBKDaeZgCBk9wA8L6U1PKVDbq3pbaS7nOL29qc3M5GJzkw7wiqqZCdY6JxPIbi43lNmCWpUj00ZCjOppab'
test_mode_key_expires_at = '2024-05-02'
test_mode_pub_key = 'pk_test_51IJyVILI8zcR9zK6cpgq7VesarlFn6TJlNEM2O1O3OpUAKqE7tVmItbNA7gtkp72DEemAXMKrRRXDGgBFKSvi0Gd00izPXa3UT'

